backend:
  name: github
  repo: DAEA-ULPGC/Juan-Luis-Jimenez
  branch: main
  auth_endpoint: "https://subtle-kitsune-cfc8c1.netlify.app/.netlify/functions/auth"

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - file: "index.md"
        label: "Página principal"
        name: "index"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Contenido", name: "body", widget: "markdown" }
