backend:
  name: github
  repo: usuario/nombre-del-repo
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Páginas"
    files:
      - file: "index.md"
        label: "Página principal"
        name: "index"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Contenido", name: "body", widget: "markdown" }
